import { College, Notification, STAGES } from './types';

// Helper to initiate complete stages set for a college
export const createDefaultStages = () => {
  const stages: Record<string, any> = {};
  const stageDefinitions = [
    { id: 'initial_meeting' },
    { id: 'product_demo' },
    { id: 'demo_followup' },
    { id: 'pricing_negotiation' },
    { id: 'mou_signing' },
    { id: 'syllabus_submission' },
    { id: 'coverage_check' },
    { id: 'coverage_communication' },
    { id: 'student_data' },
    { id: 'license_creation' },
    { id: 'impl_confirmation' },
    { id: 'implementation' },
    { id: 'impl_feedback' },
    { id: 'orientation' }
  ];
  
  stageDefinitions.forEach(s => {
    stages[s.id] = {
      status: 'not_started',
      completed_at: null,
      data: {}
    };
  });
  return stages;
};

export const getInitialNotifications = (): Notification[] => [
  { id: 'n1', role: 'admin', message: 'AC Tech (Anna University): Coverage check in progress with Content Team', timestamp: new Date(Date.now() - 3600000 * 2).toISOString(), read: false },
  { id: 'n2', role: 'admin', message: 'Saveetha Engineering College: Student data collection in progress', timestamp: new Date(Date.now() - 3600000 * 24).toISOString(), read: false },
  { id: 'n3', role: 'admin', message: 'REC Sairam College of Engineering: License creation 63% complete (240/380)', timestamp: new Date(Date.now() - 3600000 * 12).toISOString(), read: false },
  { id: 'n4', role: 'content', message: 'New syllabus assigned: AC Tech (3 units to review)', timestamp: new Date(Date.now() - 3600000 * 4).toISOString(), read: false },
  { id: 'n5', role: 'implementation', message: 'New task: Create 380 licenses for REC Sairam', timestamp: new Date(Date.now() - 3600000 * 16).toISOString(), read: false },
];

export const getInitialColleges = (): College[] => {
  const list: any[] = [
    {
      id: 'col_actech',
      name: 'AC Tech (Anna University)',
      college_type: 'Autonomous',
      academic_year: '2025-2026',
      contact_name: 'Dr. R. Velraj',
      contact_designation: 'Principal',
      phone: '+91 98765 43210',
      email: 'principal@actech.edu.in',
      location: 'Guindy, Chennai',
      total_students: '450',
      current_status: 'Following → Guindy',
      additional_comments: 'Strong interest',
      created_at: new Date(Date.now() - 3600000 * 240).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2026-04-10T10:00:00Z', data: { date: '2026-04-10', attendees: 'Principal, HOD-Maths', notes: 'Strong interest' } },
        product_demo: { status: 'completed', completed_at: '2026-04-18T14:30:00Z', data: { date: '2026-04-18', outcome: 'Very positive' } },
        demo_followup: { status: 'completed', completed_at: '2026-04-25T11:00:00Z', data: { feedback: 'Management approved' } },
        pricing_negotiation: { status: 'completed', completed_at: '2026-05-05T16:00:00Z', data: { agreed_price: '950', total_students: '450', total_value: '427500' } },
        mou_signing: { status: 'completed', completed_at: '2026-05-12T12:00:00Z', data: { mou_date: '2026-05-12' } },
        syllabus_submission: { status: 'completed', completed_at: '2026-05-15T09:00:00Z', data: { subject: 'Engineering Mathematics I', semester: 'Sem 1', units: [{ name: 'Unit 1: Matrices', topics: 'Eigen values, Cayley-Hamilton' }, { name: 'Unit 2: Differential Calculus', topics: 'Limits, Continuity' }, { name: 'Unit 3: Integral Calculus', topics: 'Definite integrals' }] } },
        coverage_check: { status: 'in_progress', completed_at: null, data: {} },
      }
    },
    {
      id: 'col_saveetha',
      name: 'Saveetha Engineering College',
      college_type: 'Autonomous',
      academic_year: '2025-2026',
      contact_name: 'Dr. S. Kumar',
      contact_designation: 'Dean',
      phone: '+91 99887 76655',
      email: 'dean@saveetha.in',
      location: 'Sriperumbudur, Chennai',
      total_students: '720',
      current_status: 'Pandiyan - Assosiative Deen- 8939977020 → Pandiyan asked send product details and proposal',
      additional_comments: 'Excellent feedback from dean regarding coverage reports.',
      created_at: new Date(Date.now() - 3600000 * 300).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2026-03-15T11:00:00Z', data: { date: '2026-03-15' } },
        product_demo: { status: 'completed', completed_at: '2026-03-22T10:30:00Z', data: { date: '2026-03-22' } },
        demo_followup: { status: 'completed', completed_at: '2026-04-02T15:00:00Z', data: {} },
        pricing_negotiation: { status: 'completed', completed_at: '2026-04-20T16:20:00Z', data: { agreed_price: '900', total_value: '648000' } },
        mou_signing: { status: 'completed', completed_at: '2026-04-28T11:00:00Z', data: {} },
        syllabus_submission: { status: 'completed', completed_at: '2026-05-02T13:00:00Z', data: { units: [{ name: 'Unit 1: Linear Algebra', topics: 'Matrices, Eigenvalues' }, { name: 'Unit 2: Calculus', topics: 'Differentiation, Integration' }] } },
        coverage_check: { status: 'completed', completed_at: '2026-05-10T14:00:00Z', data: { total_coverage: 92, unit_coverage: [{ unit: 'Unit 1', pct: 100 }, { unit: 'Unit 2', pct: 85 }] }, notes: 'Strong coverage' },
        coverage_communication: { status: 'completed', completed_at: '2026-05-12T10:00:00Z', data: {} },
        student_data: { status: 'in_progress', completed_at: null, data: {} },
      }
    },
    {
      id: 'col_sairam',
      name: 'REC Sairam College of Engineering',
      college_type: 'Affiliated',
      academic_year: '2025-2026',
      contact_name: 'Dr. M. Sasikumar',
      contact_designation: 'HOD - Mathematics',
      phone: '+91 98123 45678',
      email: 'hod.maths@sairam.edu.in',
      location: 'Tambaram, Chennai',
      total_students: '380',
      current_status: 'SAI BALAJI  MGMT -> Following up on final onboarding credential delivery',
      additional_comments: 'Licenses created. Credentials email pending onboarding day schedule.',
      created_at: new Date(Date.now() - 3600000 * 400).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2026-02-10T10:00:00Z', data: {} },
        product_demo: { status: 'completed', completed_at: '2026-02-25T14:00:00Z', data: {} },
        demo_followup: { status: 'completed', completed_at: '2026-03-08T11:00:00Z', data: {} },
        pricing_negotiation: { status: 'completed', completed_at: '2026-03-20T16:00:00Z', data: { agreed_price: '1000', total_value: '380000' } },
        mou_signing: { status: 'completed', completed_at: '2026-03-28T12:00:00Z', data: {} },
        syllabus_submission: { status: 'completed', completed_at: '2026-04-02T09:00:00Z', data: {} },
        coverage_check: { status: 'completed', completed_at: '2026-04-10T15:00:00Z', data: { total_coverage: 96 } },
        coverage_communication: { status: 'completed', completed_at: '2026-04-15T11:00:00Z', data: {} },
        student_data: { status: 'completed', completed_at: '2026-04-25T16:30:00Z', data: { student_count: 380 } },
        license_creation: { status: 'in_progress', completed_at: null, data: { licenses_created: 240, total_licenses: 380 } },
      }
    },
    {
      id: 'col_srm',
      name: 'SRM Institute of Science & Technology',
      college_type: 'Deemed',
      academic_year: '2025-2026',
      contact_name: 'Dr. P. Sathyanarayanan',
      contact_designation: 'Vice Chancellor',
      phone: '+91 99000 11223',
      email: 'vc.office@srmist.edu.in',
      location: 'Kattankulathur',
      total_students: '1200',
      current_status: 'Following → Guindy / Kattankulathur math team demo feedback.',
      additional_comments: 'Awaiting Demo to maths faculties and VC.',
      created_at: new Date(Date.now() - 3600000 * 50).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2026-05-20T11:30:00Z', data: { date: '2026-05-20', attendees: 'VC, Registrar, Dean-Engineering' } },
        product_demo: { status: 'in_progress', completed_at: null, data: { date: '2026-06-05' } },
      }
    },
    {
      id: 'col_mahendra',
      name: 'Mahendra Group of Institutions',
      college_type: 'Private',
      academic_year: '2024-2025',
      contact_name: 'Mr. Samson / Mr. Elango',
      contact_designation: 'E.D & Principal',
      phone: '+91 98765 00001',
      email: 'principal@mahendra.edu.in',
      location: 'Salem',
      total_students: '1800',
      current_status: 'HAS TO GET THE CONTACT FROM SAMSON SIR',
      additional_comments: 'Samson sir, Elango sir. They already had idea about product. IT team demo completed.',
      created_at: new Date(Date.now() - 3600000 * 600).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2025-05-22T10:00:00Z', data: { date: '2025-05-22', attendees: 'Samson sir, Elango sir', notes: 'They already had idea about product. Elango sir impressed after update.' } },
        product_demo: { status: 'completed', completed_at: '2025-06-10T14:00:00Z', data: { date: '2025-06-10', outcome: 'Met Kishore sir from IT team. White labelling discussed.' } },
        demo_followup: { status: 'completed', completed_at: '2025-06-20T11:00:00Z', data: { feedback: 'Meeting went well. Almost near closure. IT team discussion done. Awaiting Mahendra sir return for PO.' } },
      }
    },
    {
      id: 'col_jerusalem',
      name: 'Jerusalem College of Engineering',
      college_type: 'Autonomous',
      academic_year: '2024-2025',
      contact_name: 'Dr. P. Anuradha / Dr. Ramesh Sengottuvelu',
      contact_designation: 'Dean Academics / Principal',
      phone: '+91 44 22391040',
      email: 'principal@jerusalemengg.ac.in',
      location: 'Karapakkam, Chennai',
      total_students: '666',
      current_status: '26.06.2024 → We call back → 11.07.2026 | Principal | Deen Academy → If intrested we will cal back',
      additional_comments: 'Dean mam really liked the product. Principal asked Srini sir to help for closure.',
      created_at: new Date(Date.now() - 3600000 * 550).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2025-05-23T10:30:00Z', data: { date: '2025-05-23', attendees: 'Dr. P. Anuradha (Dean)' } },
        product_demo: { status: 'completed', completed_at: '2025-06-03T15:00:00Z', data: { date: '2025-06-03', outcome: 'Met principal, explained about the product. Srini sir asked to help for closure.' } },
      }
    },
    {
      id: 'col_velammal',
      name: 'Vellammal Institute of Technology',
      college_type: 'Private',
      academic_year: '2024-2025',
      contact_name: 'Dr. N. Balaji',
      contact_designation: 'Principal',
      phone: '+91 44 22446300',
      email: 'principal@velammalitech.edu.in',
      location: 'Panchetti, Chennai',
      total_students: '1800',
      current_status: 'following → Thiruninravur',
      additional_comments: 'Principal liked the product. Management level awaiting — Harsha to talk to HOD for closure.',
      created_at: new Date(Date.now() - 3600000 * 550).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2025-05-23T11:00:00Z', data: { date: '2025-05-23', attendees: 'Dr. N. Balaji (Principal)', notes: 'Principal liked the product. Management level awaiting — Harsha to talk to HOD for closure.' } },
      }
    },
    {
      id: 'col_senguthur',
      name: 'Senguthur College of Engineering',
      college_type: 'Private',
      academic_year: '2024-2025',
      contact_name: 'Dr. Sathish Kumar / Baladhandapani Sir',
      contact_designation: 'Principal / Chairman',
      phone: '+91 98765 00002',
      email: 'principal@senguthur.edu.in',
      location: 'Salem',
      total_students: '600',
      current_status: 'SENT MESSAGE AND ASK HOW TO PROCEED',
      additional_comments: 'Positive response from principal and dean academics. Baladhandapani sir to get feedback from PSNA chairman before next step.',
      created_at: new Date(Date.now() - 3600000 * 520).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2025-06-01T10:00:00Z', data: { date: '2025-06-01', attendees: 'Principal, Dean Academics', notes: 'Positive response from principal and dean academics.' } },
        product_demo: { status: 'completed', completed_at: '2025-06-18T14:30:00Z', data: { date: '2025-06-18', outcome: 'Spoke to principal and chairman. Discussed about product. Management level awaiting — Baladhandapani sir to get feedback from PSNA chairman before next step.' } },
      }
    },
    {
      id: 'col_vinayaga',
      name: 'Vinayaga Mission Krupananda Variyar Engineering College',
      college_type: 'Deemed',
      academic_year: '2024-2025',
      contact_name: 'Dr. P. Gnanasekar / Principal Sasikumar',
      contact_designation: 'Director Innovation & Industry Connect / Principal',
      phone: '+91 98765 00003',
      email: 'principal@vmkv.ac.in',
      location: 'Salem',
      total_students: '900',
      current_status: 'HCL tie-up discussion ongoing. Following up for closure.',
      additional_comments: 'Demo to maths faculties and principal — they liked the product. HCL tie-up discussion ongoing.',
      created_at: new Date(Date.now() - 3600000 * 530).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2025-05-22T09:30:00Z', data: { date: '2025-05-22', attendees: 'Dr. P. Gnanasekar, Principal Sasikumar', notes: 'Demo to maths faculties and principal — they liked the product.' } },
        product_demo: { status: 'completed', completed_at: '2025-06-20T15:00:00Z', data: { date: '2025-06-20', outcome: 'HCL tie-up discussion ongoing. Following up for closure.' } },
      }
    },
    {
      id: 'col_arasu',
      name: 'Arasu Engineering College',
      college_type: 'Private',
      academic_year: '2024-2025',
      contact_name: 'Bala Murugan',
      contact_designation: 'Principal',
      phone: '+91 98765 00004',
      email: 'principal@arasu.edu.in',
      location: 'Kumbakonam',
      total_students: '700',
      current_status: 'Student demo completed. Management level awaiting — following up with principal via Madheswaran sir.',
      additional_comments: 'Principal really liked the product. Student demo also given.',
      created_at: new Date(Date.now() - 3600000 * 550).toISOString(),
      stages: {
        initial_meeting: { status: 'completed', completed_at: '2025-05-20T10:00:00Z', data: { date: '2025-05-20', attendees: 'Principal Bala Murugan', notes: 'Principal really liked the product. Student demo also given.' } },
        product_demo: { status: 'completed', completed_at: '2025-06-05T14:00:00Z', data: { date: '2025-06-05', outcome: 'Student demo completed. Management level awaiting — following up with principal via Madheswaran sir.' } },
      }
    },
    {
      id: 'col_crescent',
      name: 'B.S. Abdur Rahman Crescent Institute of Science and Technology',
      college_type: 'Deemed',
      academic_year: '2025-2026',
      contact_name: 'Dr. Sindhu',
      contact_designation: 'Maths HOD',
      phone: '+91 99627 64781',
      email: 'hod.maths@crescent.education',
      location: 'Tambaram, Chennai',
      total_students: '800',
      current_status: 'Sindhu Mam intrested with our product, But how to move management',
      additional_comments: 'Requested to meet after September 15th.',
      created_at: new Date(Date.now() - 3600000 * 100).toISOString(),
      stages: {}
    },
    {
      id: 'col_cit',
      name: 'Chennai Institute of Technology',
      college_type: 'Autonomous',
      academic_year: '2025-2026',
      contact_name: 'Dr. Kathavarayan',
      contact_designation: 'S&H HOD',
      phone: '+91 98402 11223',
      email: 'hod.sh@cit.edu.in',
      location: 'Kundrathur, Chennai',
      total_students: '1200',
      current_status: 'I discussed with Principal and he told i discussed with cherman and tell u | Following, JAN 2ND',
      additional_comments: 'Staff and principal discussed, requested demo logins.',
      created_at: new Date(Date.now() - 3600000 * 110).toISOString(),
      stages: {
        pricing_negotiation: { status: 'in_progress', completed_at: null, data: { notes: 'Closure stage' } }
      }
    },
    {
      id: 'col_excel',
      name: 'Excel Engineering College',
      college_type: 'Autonomous',
      academic_year: '2025-2026',
      contact_name: 'Dr. Priya',
      contact_designation: 'COE / Dean',
      phone: '+91 94432 02931',
      email: 'coe@excel.education',
      location: 'Salem',
      total_students: '1100',
      current_status: 'coe liked the product, coe, he said give me one login access and hel set up zoom demo with principal',
      additional_comments: 'Completed high-level zoom call with Controller of Exams. Very interested in autonomous syllabus alignment.',
      created_at: new Date(Date.now() - 3600000 * 80).toISOString(),
      stages: {
        pricing_negotiation: { status: 'in_progress', completed_at: null, data: { notes: 'Closure stage' } }
      }
    }
  ];

  // Bootstrap all other raw colleges mentioned in the prototype to match full list
  const extraColleges = [
    { name: 'A.R. Engineering College Villupuram Chennai (AREC)', location: 'Villupuram', current_status: 'Villupuram' },
    { name: 'AMET Institute of Science & Technology', location: 'Chennai', current_status: 'Mam told aug 15th i will call u back. Assistant Registrar told i will give one day for demo', phone: '+91 9976507552', contact_name: 'Mehetraj Mam Maths Staff' },
    { name: 'ARM College of Engineering and Technology', location: 'Tambaram, Chennai', current_status: 'Tambaram' },
    { name: 'ATRIA', location: 'BANGALORE', current_status: 'Seeking math pipeline connection' },
    { name: 'AVC ENGINEERING', location: 'Mayavaram', current_status: 'KAVITHA CHEMISTRY HOD. SENT INTRODUCTION MESSAGE', contact_name: 'KAVITHA CHEMISTRY HOD' },
    { name: 'AVC POLYTECHNIC, MAYAVARAM', location: 'Mayavaram', current_status: 'MR VALAVAN. SENT MESSAGE' },
    { name: 'AVS ENGINEERING', location: 'Salem', current_status: 'SARAVANAN SIR PHYSICS HOD. SENT MESSAGE' },
    { name: 'Aalim Muhammed Salegh College of Engineering', location: 'Thiruninravur, Chennai', current_status: 'Following → Thiruninravur' },
    { name: 'Aarupadai Veedu Institute of Technology(Vinayaga Mission)', location: 'Karapakkam, Chennai', current_status: 'Maths HOD Interested, How to move the Management Level → Karapakkam', phone: '9940249593', contact_name: 'Maths Staff - Gayathri' },
    { name: 'Abdul Hakem College', location: 'Vellore', current_status: 'PRICIPAL SASIKUMAR SHARED NEW NUMBER OF MATHS FACULTY. GAVE AN IDEA ABOUT PRODUCT.', contact_name: 'PLACEMENT DIRECTOR DR KADHER' },
    { name: 'Acharya Pathashala', location: 'Kanakapura, Karnataka', current_status: 'ref of Rajshekhar Patil', contact_name: 'Shivmurthiah' },
    { name: 'Adhiparasakthi Engineering College, Hosur', location: 'Hosur', current_status: 'TOMORROW AFTERNOON MEETING FIXED WITH MATHS TEAM, PRAMILA', contact_name: 'PRINCIPAL R.NATH' },
    { name: 'Agni College of Technology', location: 'Chennai', current_status: 'Spoke to principal, told feedback from HOD that product not required now' },
    { name: 'Akshaya Engineering College', location: 'Coimbatore', current_status: 'DR NIRMALA 1ST YEAR HOD. SENT MESSAGE', contact_name: 'DR NIRMALA 1ST YEAR HOD' },
    { name: 'Alagappa College of Technology', location: 'Guindy, Chennai', current_status: 'Following → Guindy', contact_name: 'Dean Chamber : 044 2235 9101' },
    { name: 'Alpha College of Engineering', location: 'Poonamallee, Chennai', current_status: 'Jeevitha - Principal assistant - 9884487551. Meet with Principal.', phone: '914426495211' },
    { name: 'Alvas Institute of technology Mudbidre', location: 'Moodbidri, Karnataka', current_status: 'Ref from Bangalore dean pool', contact_name: 'Dattatraya Gujjar Dean' },
    { name: 'Anand Institute of Higher Technology', location: 'Karapakkam, Chennai', current_status: 'Maths Staff satisfied | But Principal not ready to see our product' },
    { name: 'Angel Engineering College', location: 'Coimbatore', current_status: 'SPOKE TO MOHANASUNDARI MAM. intro done. follow back.', contact_name: 'MOHANASUNDARI MATHS PROFESSOR' },
    { name: 'Annai Teresa College of Engineering', location: 'Villupuram', current_status: 'Villupuram regional track' },
    { name: 'Annai Veilankanni’s College of Engineering', location: 'Tambaram, Chennai', current_status: 'Meet - Principal → No Responce → Tambaram' },
    { name: 'Annai mira', location: 'Ranipet', current_status: 'Syllabus and coverage check follow back' },
    { name: 'Annapoorna Engineeering College', location: 'Salem', current_status: 'SPOKE TO KUMAR MATHS HOD, ZOOM CALL OVER', contact_name: 'KUMAR MATHS HOD' },
    { name: 'Apollo Engineering College', location: 'Poonamallee, Chennai', current_status: 'Poonamallee pipeline' },
    { name: 'Arifa Engineering College', location: 'Kumbakonam', current_status: 'MR VAIDHIYANATHAN. SENT MESSAGE' },
    { name: 'Arignar Anna Institute of Science and Technology', location: 'Sriperumbudur, Chennai', current_status: 'Closed → Sriperumbudur' },
    { name: 'ARM College of Engineering and Technology', location: 'Chennai', current_status: 'Tambaram track, followup scheduled' },
    { name: 'Arul Murugan Engineering', location: 'Karur', current_status: 'PONNUSAMY MATHS FACULTY. SENT MESSAGE' },
    { name: 'BM SIT', location: 'BANGALORE', current_status: 'Ref from regional sales team' },
    { name: 'Balaji institute of Engineering and Technology', location: 'Karapakkam, Chennai', current_status: 'Closed → Karapakkam' },
    { name: 'Barathi Engineering College', location: 'Chennai', current_status: 'TRUSTEE KRISHNAMURTHY SIR. Awaiting zoom callback', contact_name: 'CHAIRMAN SIR DHANASEKAR' },
    { name: 'Bhajarang Engineering College', location: 'Poonamallee, Chennai', current_status: 'Poonamallee area track' },
    { name: 'Bharath Institute of Higher Education and Research (BIHER)', location: 'Chennai', current_status: 'ASK SIR TO CLOSE, THEY ALREADY KNOW THE PRODUCT' },
    { name: 'Builders Engineering College', location: 'Erode', current_status: 'SPOKE TO SAMPATH, HE HAS TO TELL THANGARAJ SIR' },
    { name: 'CBIT', location: 'KOLAR, Karnataka', current_status: 'Atria group reference', contact_name: 'NISHANTH' },
    { name: 'CIET', location: 'Coimbatore', current_status: 'SPOKE TO MOHANAPRIYA. ZOOM DONE WENT REALLY WELL', contact_name: 'MOHANAPRIYA MATHS HOD' },
    { name: 'Cape Institute Of Technology', location: 'Kanyakumari', current_status: 'ASHOK EEE HOD. SENT MESSAGE' },
    { name: 'Chanakya University', location: 'Haralur, Karnataka', current_status: 'Dean positive about content platform', contact_name: 'Anilkumar Garag Dean' },
    { name: 'Christ Engineering College', location: 'BANGALORE', current_status: 'Syllabus alignment discussion' },
    { name: 'DASTM', location: 'UDAYAPURA, Karnataka', current_status: 'Principal ref', contact_name: 'Ravishankar Principal' },
    { name: 'DMI ENGINEERING COLLEGE', location: 'Chennai', current_status: 'SENT MESSAGE CONTACT TO PROCEED' },
    { name: 'Dayananda Sagar University', location: 'Bangalore', current_status: 'VC level introduction scheduled', contact_name: 'Puttamadappa' },
    { name: 'Dhaanish Ahmed College Of Engineering', location: 'Tambaram, Chennai', current_status: 'Tambaram area follow up' },
    { name: 'Dhanalakshmi Srinivasan College', location: 'Perambalur', current_status: 'MEETING FIXED ON 15TH FEBRUARY, CONFIRM WITH HIM AGAIN' },
    { name: 'Dr. M.G.R. Educational and Research Institute', location: 'Poonamallee, Chennai', current_status: 'Following → Dev track' },
    { name: 'EBET', location: 'Erode', current_status: 'SPOKE TO THANGARAJ DIRECTOR, HE SAID STATUS WITH HOD' },
    { name: 'EGS PILLAI', location: 'Nagapattinam', current_status: 'Autonomous syllabus review requested' },
    { name: 'GKM College of Engineering and Technology (GKMCET)', location: 'Tambaram, Chennai', current_status: 'Maths HOD Arasan - 9444452503 | meeting March month', contact_name: 'HOD Arasan' },
    { name: 'Gandhi Polytechnic', location: 'Salem', current_status: 'PRINCIPAL SAKTHIVEL. SENT MESSAGE' },
    { name: 'Ganesh Engineering College', location: 'Salem', current_status: 'MANGAIYAKARASI MATHS. DONT WANT ONLINE PRODUCT. CONNECT MGMT.', contact_name: 'MANGAIYAKARASI MATHS PROFESSOR' },
    { name: 'Gojan School of Business and Technology', location: 'Avadi, Chennai', current_status: 'Avadi location pipeline' },
    { name: 'Hindustan Chennai', location: 'COIMBATORE', current_status: 'Lot of work, call next month' },
    { name: 'IFET College of Engineering', location: 'Villupuram', current_status: 'Villupuram regional leader' },
    { name: 'IRTT ENGINEERING', location: 'Erode', current_status: 'ZOOM CALL OVER | SENT MESSAGE', contact_name: 'DR RAJESWARI MATHS HOD' },
    { name: 'Imayam Engineering', location: 'Trichy', current_status: 'ZOOM MEETING OVER. Positive feedback. Chairman approval pending.', contact_name: 'CHAIRMAN SIR' },
    { name: 'Indira College', location: 'Chennai', current_status: 'refer indira mam and talk', contact_name: 'Thanikesan - CS HOD' },
    { name: 'Indra Ganesan', location: 'Trichy', current_status: 'Demo requested' },
    { name: 'J.N.N Institute of Engineering', location: 'Thiruninravur, Chennai', current_status: 'Thiruninravur pipeline' },
    { name: 'JANSONS', location: 'Coimbatore', current_status: 'HOD demonstration requested' },
    { name: 'JCET - Jaya College of Engineering and Technology', location: 'Chennai', current_status: 'WHATSAPP SENT. CALL AFTER PONGAL FOR DEMO', email: 'principaljcetec@gmail.com' },
    { name: 'JCT', location: 'COIMBATORE', current_status: 'Region check' },
    { name: 'JIT - Jaya Institute of Technology', location: 'Thiruvallur', current_status: 'Meet Me on After Pongal', contact_name: 'Raagu - Principal' },
    { name: 'JJ', location: 'TRICHY', current_status: 'Trichy regional review' },
    { name: 'JKK-MUNIRAJAH', location: 'Erode', current_status: 'SATHYA BALAJI HOD. Spoke a bit negative.', contact_name: 'SATHYA BALAJI HOD' },
    { name: 'JSEC - Jaya Sakthi Engineering College', location: 'Poonamallee, Chennai', current_status: 'Poonamallee track' },
    { name: 'Jain University', location: 'Jayanagar, Bengaluru', current_status: 'Dean academics introduction', contact_name: 'Kiran S Dean Academics' },
    { name: 'Jappiaar University', location: 'Chennai', current_status: 'Baskaran told to meet Registrar Binu sivasing', phone: '+91 9444425785', contact_name: 'Pro Vice Chancellor' },
    { name: 'Jawahar Engineering College', location: 'Guindy, Chennai', current_status: 'Guindy line area' },
    { name: 'Jayalakshmi Institute Of Technology', location: 'Dharmapuri', current_status: 'SPOKE TO DR TAMIL POSITIVE FEEDBACK. CALL TO CONFIRM ZOOM.' },
    { name: 'Jeppiaar Engineering College', location: 'Chennai', current_status: 'Titus mam positive, VC pending decision', contact_name: 'Maths HOD Titus' },
    { name: 'Jeppiaar Institute of Technology', location: 'Sriperumbudur, Chennai', current_status: 'Get appointment and come' },
    { name: 'Jeppiaar Maamallan Engineering College', location: 'Sriperumbudur, Chennai', current_status: 'Closed → Sriperumbudur' },
    { name: 'KCG College of Technology', location: 'Karapakkam, Chennai', current_status: 'HOD told discussed with staffs' },
    { name: 'KGISL', location: 'Coimbatore', current_status: 'AO Mr Dhavamani contacted', contact_name: 'MR DHAVAMANI COLLEGE AO' },
    { name: 'KKIT', location: 'Coimbatore', current_status: 'Yamuna mam meeting after 10 July', contact_name: 'Yamuna maths HOD' },
    { name: 'KSR', location: 'Salem', current_status: 'THEY KNOW PRODUCT AND SIR HAS TO CLOSE THIS', contact_name: 'SRINIVASAN CHAIRMAN' },
    { name: 'KalaignarKarunanidhi Institute Of Technology', location: 'Coimbatore', current_status: 'Syllabus alignment review' },
    { name: 'Kalinga University', location: 'Chennai', current_status: 'Guindy coordinator' },
    { name: 'Kamaraj Engineering College', location: 'Virudhunagar', current_status: 'Sent mail to maths department', contact_name: 'MEENAKSHI HOD CS' },
    { name: 'Karpaga Vinayaga College of Engineering and Technology', location: 'Sriperumbudur, Chennai', current_status: 'Sriperumbudur corridor' },
    { name: 'Karpagam', location: 'Coimbatore', current_status: 'Introduction done' },
    { name: 'Kaveri College', location: 'Salem', current_status: 'REVATHI MAM mid of meeting. bhaskar sir unreachable', contact_name: 'DURAISAMY SIR PRINCIPAL' },
    { name: 'Kings Engineering College', location: 'Sriperumbudur, Chennai', current_status: 'Principal - Get appointment on Monday' },
    { name: 'Kishkinda University', location: 'Ballari, Karnataka', current_status: 'Director VC reference', contact_name: 'Prithviraj Bhupal Director' },
    { name: 'Krishna College, Cbe', location: 'COIMBATORE', current_status: 'Demanded syllabus alignment details' },
    { name: 'Krishnasamy College, Cuddalore', location: 'Cuddalore', current_status: 'Need contact to proceed', contact_name: 'DR KRISHNA SAMY CHAIRMAN' },
    { name: 'Kumaraguru', location: 'Coimbatore', current_status: 'Sivakumar HOD satisfied', contact_name: 'SIVAKUMAR 1ST YEAR HOD' },
    { name: 'Kumarasamy College', location: 'Karur', current_status: 'chithrala not picking, jagadeesan sir called', contact_name: 'KUPPUSAMY DIRECTOR' },
    { name: 'Loyola - ICAM College of Engineering and Technology', location: 'Guindy, Chennai', current_status: 'Guindy regional group', contact_name: 'Principal - Antony' },
    { name: 'Loyola Institute of Technology', location: 'Poonamallee, Chennai', current_status: 'Meet with Principal Jan 1st week', contact_name: 'Seenikannan - Principal' },
    { name: 'MAMCE', location: 'TRICHY', current_status: 'MAM group' },
    { name: 'MAMCET', location: 'TRICHY', current_status: 'pricing in progress' },
    { name: 'MANAKULA', location: 'Pondicherry', current_status: 'Meeting done' },
    { name: 'MET ENGINEERING', location: 'Nagercoil', current_status: 'Chairman sir number received' },
    { name: 'MNM JAIN', location: 'Karapakkam, Chennai', current_status: 'VISIT COLLEGE, PRINCIPAL ZOOM' },
    { name: 'MVIT', location: 'BANGALORE', current_status: 'TRUSTEE VISIT PLANNED', contact_name: 'SUDEEP' },
    { name: 'Madha Engineering College', location: 'Tambaram, Chennai', current_status: 'documents sent' },
    { name: 'Madras Institute of Technology', location: 'Tambaram, Chennai', current_status: 'Basker told to get opinion from staffs', contact_name: 'S&H HOD' },
    { name: 'Mohanbabu University Tirupati', location: 'Tirupati, AP', current_status: 'VC Nagaraj Ramrao reference', contact_name: 'Nagaraj Ramrao VC MBU' },
    { name: 'Muthayammal Engineering College', location: 'Salem', current_status: 'Elavarasan feedback shared, Principal followup' },
    { name: 'N NPR DINDIGUL', location: 'Dindigul', current_status: 'Dindigul area followup' },
    { name: 'Nanda Engineering College', location: 'Erode', current_status: 'SENT MESSAGE', contact_name: 'THIRUNEELAGANDAN 1ST YEAR HOD' },
    { name: 'National Engineering College', location: 'Kovilpatti', current_status: 'SENT MESSAGE' },
    { name: 'Nellai Engineering College', location: 'Tirunelveli', current_status: 'PEER MOHAMMED reference' },
    { name: 'New Prince Shri Bhavani College Of Engineering & Technology', location: 'Karapakkam, Chennai', current_status: 'Principal told if need they will call' },
    { name: 'P.B. College of Engineering', location: 'Sriperumbudur, Chennai', current_status: 'Principal not interested', contact_name: 'Principal - Nagaraj' },
    { name: 'Panimalar Engineering College', location: 'Poonamallee, Chennai', current_status: 'Poonamallee region' },
    { name: 'Panimalar Institute of Technology', location: 'Poonamallee, Chennai', current_status: 'Poonamallee region' },
    { name: 'Park Engineering College', location: 'Coimbatore', current_status: 'SENT MESSAGE', contact_name: 'DR LAKSHMANAN PRINCIPAL' },
    { name: 'Peri Institute Of Technology', location: 'Tambaram, Chennai', current_status: 'HOD Satisfied, Principal meeting' },
    { name: 'Prathyusha Engineering College', location: 'Sriperumbudur, Chennai', current_status: 'Not interested. Got negative review from staff.' },
    { name: 'Prince Dr. K. Vasudevan College of Engineering and Technology', location: 'Karapakkam, Chennai', current_status: 'Principal told management not interested', contact_name: 'Principal - Sundar Selvin' },
    { name: 'Prince Shri Venkateshwara Padmavathy Engineering College', location: 'Karapakkam, Chennai', current_status: 'Need free access, admission going', contact_name: 'Principal - G.Indira' },
    { name: 'RMK', location: 'Chennai', current_status: 'Everything ok, need good feedback from math staff' },
    { name: 'RN SIT', location: 'BANGALORE', current_status: 'Regional search' },
    { name: 'RVS - CET', location: 'Coimbatore', current_status: 'Maths staff did not show interest', contact_name: 'MOHAN PRINCIPAL' },
    { name: 'RVS FOE', location: 'Dindigul', current_status: 'Spoken to Chairman. Vijayarajan refer.', contact_name: 'VIJAYAN PRINCIPAL' },
    { name: 'Rajiv Gandhi College of Engineering', location: 'Sriperumbudur, Chennai', current_status: 'Meet on next week', contact_name: 'Vice Principal - Gobinath' },
    { name: 'Rangaboopathy', location: 'Villupuram', current_status: 'Sathiyampurthy: next semester', contact_name: 'KARTHIKEYAN' },
    { name: 'SAI RAM', location: 'Chennai', current_status: 'Positive feedback from math senior staff', contact_name: 'SAI BALAJI MGMT' },
    { name: 'SOLAMALAI', location: 'Madurai', current_status: 'pricing in progress' },
    { name: 'SONA ENGINEERING COLLEGE', location: 'Salem', current_status: 'Saravanan sir syllabus discussion', contact_name: 'MR SARAVANAN' },
    { name: 'SRM Sikkhim', location: 'Sikkim', current_status: 'Awaiting regional update' },
    { name: 'SVIT', location: 'BANGALORE', current_status: 'Syllabus mapping', contact_name: 'SHYAM' },
    { name: 'Siddaganga Institute Of Technology', location: 'Tumkur, Karnataka', current_status: 'Principal level introduction', contact_name: 'Dr. Narendra Vishwanath Principal' },
    { name: 'Skp Engineering College', location: 'Tiruvannamalai', current_status: 'SPOKE TO PRINCIPAL BHASKAR. PROPOSAL SENT.', contact_name: 'BHASKAR PRINCIPAL' },
    { name: 'Sri Easwar', location: 'Coimbatore', current_status: 'Demo scheduled' },
    { name: 'Sri Jayaram Institute Of Engineering And Technology', location: 'GummidiPundi, Chennai', current_status: 'GummidiPundi track' },
    { name: 'Sri Krishna Engineering College', location: 'Tambaram, Chennai', current_status: 'Vijay sir told to meet late Feb', contact_name: 'Maths HOD - Vijay' },
    { name: 'Sri Muthukumaran Institute Of Technology', location: 'Poonamallee, Chennai', current_status: 'Meet on next week', contact_name: 'Principal - Somasundaram' },
    { name: 'Sri Ramanujar Engineering College', location: 'Tambaram, Chennai', current_status: 'Feb mid got appointment', contact_name: 'maths HOD Kumaresan' },
    { name: 'Sri Sai Ram Institute Of Technology', location: 'Tambaram, Chennai', current_status: 'Maths HOD Balaji following', contact_name: 'Maths HOD - Balaji' },
    { name: 'Srinivas University', location: 'Mangaluru, Karnataka', current_status: 'VC demonstration', contact_name: 'Satyanarayan Reddy K VC' },
    { name: 'Srm Easwari Engineering', location: 'Poonamallee, Chennai', current_status: 'Poonamallee line' },
    { name: 'Srm Valliammai Engineering College', location: 'Tambaram, Chennai', current_status: 'Tambaram line group' },
    { name: 'Ssn College Of Engineering', location: 'Karapakkam, Chennai', current_status: 'Maths HOD Prabas told if need will call', contact_name: 'Maths HOD Prabas' },
    { name: 'St Joseph Engineering College', location: 'Chennai', current_status: 'Deen told file moved to Chairman, need 1 week' },
    { name: 'St. Joseph\'S College Of Engineering', location: 'Karapakkam, Chennai', current_status: 'Maths HOD Meena Devi principal not interested', contact_name: 'Maths HOD - Meena Devi' },
    { name: 'Tagore Engineering College', location: 'Tambaram, Chennai', current_status: 'Feb last week got appointment', contact_name: 'Maths HOD-Agasthi' },
    { name: 'Tamilnadu College Of Engineering', location: 'Coimbatore', current_status: 'Santhivel Murugan principal busy, call later', contact_name: 'SHAKTHI VEL MURUGAN' },
    { name: 'Thangavelu Engineering College', location: 'Karapakkam, Chennai', current_status: 'Gracee keerthi placement following', contact_name: 'Principal - Venkatesan' },
    { name: 'TJ COLLEGE // THANGAVEL COLLEGE, KARAPAKKAM', location: 'Karapakkam, Chennai', current_status: 'SPOKEN/ CALL FOR CLOSURE AFTER PONGAL 1.5 + GST', contact_name: 'PRINCIPAL VENKATESH' },
    { name: 'Vel Tech Dr.Rangarajan Dr.Sakunthala College', location: 'Avadi, Chennai', current_status: 'Avadi corridor' },
    { name: 'VELS Institute (VISTAS)', location: 'Tambaram, Chennai', current_status: 'Tambaram Corridor' },
    { name: 'VELTECH', location: 'Chennai', current_status: 'Vijayram placement officer following' },
    { name: 'Vivekananda', location: 'Tiruchengode', current_status: 'Renewal and reusage discussions', contact_name: 'VIJAYKUMAR PRINCIPAL' },
  ];

  extraColleges.forEach((c, idx) => {
    list.push({
      id: `col_extra_${idx}`,
      name: c.name,
      college_type: 'Affiliated',
      academic_year: '2025-2026',
      contact_name: c.contact_name || '',
      contact_designation: 'HOD / Placements',
      phone: c.phone || '',
      email: '',
      location: c.location || 'Tamil Nadu',
      total_students: '500',
      current_status: c.current_status,
      additional_comments: '',
      created_at: new Date(Date.now() - 3600000 * (idx + 100)).toISOString(),
      stages: createDefaultStages()
    });
  });

  // For any colleges which do not have stage progress filled, make sure they have the full default stages initialized
  list.forEach(c => {
    if (!c.stages) {
      c.stages = createDefaultStages();
    } else {
      const def = createDefaultStages();
      c.stages = { ...def, ...c.stages };
    }
  });

  return list;
};
